# Generated by Django 5.0.6 on 2024-06-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_book_book_id_book_reserved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reserved_by',
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default=None, upload_to='book_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
