# Generated by Django 5.0.6 on 2024-06-26 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_book_book_id_remove_book_borrowed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='Borrow',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='borrowed_on',
            new_name='borrowed_at',
        ),
    ]
